[pytest]
addopts = -s -v
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    dashboard: Маркировка для тестов, связанных с рабочей панелью
    registration: Маркировка для тестов регистрации
    regression: Маркировка для регрессионных тестов
    authorization: Маркировка для тестов авторизации
    courses: Маркировка для тестов курсов
