[pytest]
addopts = -s -v
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    ui: Маркировка для UI тестов
    slow: Маркировка для медленных тестов
    smoke: Маркировка для смоук тестов
    critical: Маркировка для критичных тестов
    dashboard: Маркировка для тестов, связанных с рабочей панелью
    registration: Маркировка для тестов регистрации
    regression: Маркировка для регрессионных тестов
    authorization: Маркировка для тестов авторизации
    courses: Маркировка для тестов курсов
